ARG BASE_IMAGE=gcr.io/kf-feast/spark-py-base:v3.0.1

FROM ${BASE_IMAGE}

USER root
ADD https://repo1.maven.org/maven2/com/linkedin/sparktfrecord/spark-tfrecord_2.12/0.3.0/spark-tfrecord_2.12-0.3.0.jar /opt/spark/jars
